### ISSUE TITLE
the script can't get the image's size

### ISSUE THREAD

**Issue by gpapin** [vlanard/videoscripts#11]
The script fail when I try to get the geometry from the previously generated thumbfiles.
I've checked and they are on disk - so I wonder what's going on.

Here is the line that trigger the exception
```coords = get_geometry(thumbfiles[0]) #use the first file (since they are all same size) to get geometry settings```

Here is the exception:
```
ERROR   [2016-11-10 17:36:34.543343] An exception occurred
None
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "sprites/makesprites.py", line 298, in <module>
    run(task)
  File "sprites/makesprites.py", line 263, in run
    coords = get_geometry(thumbfiles[0]) #use the first file (since they are all same size) to get geometry settings
  File "sprites/makesprites.py", line 144, in get_geometry
    geom = doCmd("""identify -format "%%g - %%f\n" %s""" % pipes.quote(file))
  File "sprites/makesprites.py", line 97, in doCmd
    raise e #todo ?
OSError: [Errno 2] No such file or directory
```

**Comment by skyisboss** [comment]
打开  makesprites.py
查找  sips --resampleWidth 替换成 mogrify -geometry
我是这样做就解决问题了
或者 USE_SIPS = False
